# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True, verbose_name='Post date published')),
                ('name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=30, verbose_name='Тема')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщение',
            },
        ),
    ]
